package functions

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

// shimMarker is printed by the generated main once it is listening. The parent
// reads it instead of polling a port, which keeps startup deterministic and
// needs no sleeping.
const shimMarker = "CLOUDRIG_LISTEN "

// shim is the generated main. It binds first and announces the real address,
// so the caller never has to guess a port or race the child.
var shim = template.Must(template.New("main").Parse(`// Code generated by cloudrig. DO NOT EDIT.
package main

import (
	"fmt"
	"log"
	"net"
	"net/http"

	fn {{ printf "%q" .ImportPath }}
)

func main() {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		log.Fatalf("cloudrig shim: listen: %v", err)
	}
	fmt.Printf({{ printf "%q" .Marker }} + "%s\n", ln.Addr().String())

	mux := http.NewServeMux()
	mux.HandleFunc("/", fn.{{ .EntryPoint }})
	if err := http.Serve(ln, mux); err != nil {
		log.Fatalf("cloudrig shim: serve: %v", err)
	}
}
`))

// pkgInfo is the slice of go list output we need, plus the environment the
// rest of the toolchain calls must reuse to see the same module.
type pkgInfo struct {
	ImportPath string
	Module     struct{ Dir string }

	env []string
}

// goLauncher compiles a generated main that imports the function package.
type goLauncher struct{}

func (goLauncher) prepare(ctx context.Context, f Function) (spec, error) {
	if err := checkEntryPoint(f.Source, f.EntryPoint); err != nil {
		return spec{}, fmt.Errorf("function %s: %w", f.Name, err)
	}
	bin, cleanup, err := build(ctx, f)
	if err != nil {
		return spec{}, err
	}
	return spec{
		// Not CommandContext: the child outlives the call that started it.
		// See the note in node.go.
		cmd:     exec.Command(bin),
		cleanup: cleanup,
		// The Go shim binds its own port and prints it, so no port has to be
		// reserved and no startup race exists.
		ready: func(line string) (string, bool) {
			if !strings.HasPrefix(line, shimMarker) {
				return "", false
			}
			return strings.TrimPrefix(line, shimMarker), true
		},
	}, nil
}

// build compiles fn into a binary and returns its path plus a cleanup func.
func build(ctx context.Context, f Function) (bin string, cleanup func(), err error) {
	info, err := listPackage(ctx, f.Source)
	if err != nil {
		return "", nil, err
	}
	if info.Module.Dir == "" {
		return "", nil, fmt.Errorf("%s is not inside a Go module", f.Source)
	}

	// The shim must live inside the function's own module, or its import of
	// the function package will not resolve.
	genDir, err := os.MkdirTemp(info.Module.Dir, ".cloudrig-build-")
	if err != nil {
		return "", nil, fmt.Errorf("creating build dir: %w", err)
	}
	removeGen := func() { _ = os.RemoveAll(genDir) }

	var src strings.Builder
	if err := shim.Execute(&src, map[string]string{
		"ImportPath": info.ImportPath,
		"EntryPoint": f.EntryPoint,
		"Marker":     shimMarker,
	}); err != nil {
		removeGen()
		return "", nil, fmt.Errorf("generating shim: %w", err)
	}
	if err := os.WriteFile(filepath.Join(genDir, "main.go"), []byte(src.String()), fs.FileMode(0o600)); err != nil {
		removeGen()
		return "", nil, fmt.Errorf("writing shim: %w", err)
	}

	outDir, err := os.MkdirTemp("", "cloudrig-fn-")
	if err != nil {
		removeGen()
		return "", nil, fmt.Errorf("creating output dir: %w", err)
	}
	bin = filepath.Join(outDir, "fn"+exeSuffix())

	rel, err := filepath.Rel(info.Module.Dir, genDir)
	if err != nil {
		removeGen()
		_ = os.RemoveAll(outDir)
		return "", nil, err
	}

	cmd := exec.CommandContext(ctx, "go", "build", "-o", bin, "./"+filepath.ToSlash(rel))
	cmd.Dir = info.Module.Dir
	cmd.Env = append(os.Environ(), info.env...)
	if out, err := cmd.CombinedOutput(); err != nil {
		removeGen()
		_ = os.RemoveAll(outDir)
		return "", nil, fmt.Errorf("building %s: %w\n%s", f.Name, err, out)
	}

	// The generated source is disposable once compiled; the binary is not.
	removeGen()
	return bin, func() { _ = os.RemoveAll(outDir) }, nil
}

func listPackage(ctx context.Context, dir string) (pkgInfo, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return pkgInfo{}, err
	}
	if _, err := os.Stat(abs); err != nil {
		return pkgInfo{}, fmt.Errorf("function directory %s: %w", dir, err)
	}

	// The workspace comes first, so a function that deliberately resolves
	// against local modules keeps working.
	info, err := runList(ctx, dir, abs, nil)
	if err == nil {
		return info, nil
	}

	// A source directory with its own go.mod is self-contained, but a go.work
	// that does not `use` it makes the toolchain refuse the package outright.
	// Falling back outside the workspace is what the user meant by pointing at
	// that directory.
	if exists(filepath.Join(abs, "go.mod")) {
		standalone := []string{"GOWORK=off"}
		if info, offErr := runList(ctx, dir, abs, standalone); offErr == nil {
			info.env = standalone
			return info, nil
		}
	}
	return pkgInfo{}, err
}

func runList(ctx context.Context, dir, abs string, env []string) (pkgInfo, error) {
	cmd := exec.CommandContext(ctx, "go", "list", "-json", ".")
	cmd.Dir = abs
	cmd.Env = append(os.Environ(), env...)

	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) && len(ee.Stderr) > 0 {
			return pkgInfo{}, fmt.Errorf("go list in %s: %s", dir, strings.TrimSpace(string(ee.Stderr)))
		}
		return pkgInfo{}, fmt.Errorf("go list in %s: %w", dir, err)
	}

	var info pkgInfo
	if err := json.Unmarshal(out, &info); err != nil {
		return pkgInfo{}, fmt.Errorf("parsing go list output: %w", err)
	}
	return info, nil
}
